# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_station', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
                ('tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='traffic_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trafic_id', models.CharField(default='c001', max_length=20)),
                ('start_station', models.CharField(max_length=20)),
                ('aim_station', models.CharField(max_length=20)),
                ('start_data', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('aim_data', models.CharField(max_length=20)),
                ('aim_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_ticket',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('start_station', models.CharField(max_length=20)),
                ('aim_station', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
                ('tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwords', models.CharField(max_length=20)),
            ],
        ),
    ]
