# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20180607_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesman',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='space',
            name='data',
        ),
        migrations.RemoveField(
            model_name='space',
            name='id',
        ),
        migrations.RemoveField(
            model_name='traffic_information',
            name='aim_data',
        ),
        migrations.RemoveField(
            model_name='traffic_information',
            name='start_data',
        ),
        migrations.RemoveField(
            model_name='user_ticket',
            name='data',
        ),
        migrations.RemoveField(
            model_name='user_ticket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_ticket',
            name='tickets',
        ),
        migrations.AddField(
            model_name='traffic_information',
            name='mileage',
            field=models.CharField(default='100km', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traffic_information',
            name='train_type',
            field=models.CharField(default='100', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='telphone',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='aim_station',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='space',
            name='tickets',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_ticket',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
