# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_auto_20180619_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telphone',
            field=models.IntegerField(max_length=30),
        ),
    ]
