# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_auto_20180619_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telphone',
            field=models.CharField(max_length=20),
        ),
    ]
