# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_auto_20180619_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='passwd',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
