# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_salesman_passwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesman',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='passwd',
        ),
    ]
