# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_auto_20180624_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
