# Generated by Django 2.2.1 on 2019-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightId', models.CharField(max_length=10)),
                ('flightName', models.CharField(max_length=20)),
                ('flightType', models.CharField(max_length=20)),
                ('flightCompany', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=20)),
                ('arriveTime', models.CharField(max_length=20)),
                ('startCity', models.CharField(max_length=20)),
                ('arriveCity', models.CharField(max_length=20)),
                ('flyTime', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
                ('fare', models.CharField(max_length=20)),
                ('discountRate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='travelagency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('No', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('officeAddress', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('ID', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='userTicket',
            fields=[
                ('userTicketsId', models.IntegerField(primary_key=True, serialize=False)),
                ('flightId', models.CharField(max_length=10, null=True)),
                ('username', models.CharField(max_length=18, null=True)),
            ],
        ),
    ]
