# Generated by Django 2.2.1 on 2019-05-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyTicket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
