# Generated by Django 2.2.1 on 2019-05-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyTicket', '0002_userticket_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTicketView',
            fields=[
                ('flightName', models.CharField(max_length=20)),
                ('flightType', models.CharField(max_length=20)),
                ('flightCompany', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=20)),
                ('arriveTime', models.CharField(max_length=20)),
                ('startCity', models.CharField(max_length=20)),
                ('arriveCity', models.CharField(max_length=20)),
                ('flyTime', models.CharField(max_length=20)),
                ('fare', models.CharField(max_length=20)),
                ('discountRate', models.CharField(max_length=20)),
                ('userTicketsId', models.IntegerField(primary_key=True, serialize=False)),
                ('flightId', models.CharField(max_length=10, null=True)),
                ('seats', models.IntegerField()),
                ('username', models.CharField(max_length=18, null=True)),
            ],
            options={
                'db_table': 'userTicketView',
            },
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='id',
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='No',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
